services:
  db:
    image: postgres:latest
    container_name: linguavault_db
    restart: always
    environment:
      POSTGRES_USER: mogumogu
      POSTGRES_PASSWORD: mogumogu
      POSTGRES_DB: linguavault_db
    ports:
      - "54321:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mogumogu -d linguavault_db"]
      interval: 10s
      timeout: 5s
      retries: 5